### ISSUE TITLE
Cannot read property 'bind' of null

### ISSUE THREAD

**Issue by johnpool3** [HBYoon/node-mysql-transaction#3]
Hi,
I'm getting this error after updating node to 0.12.0.

/node_modules/node-mysql-transaction/lib/chain.js:150:40

Looks like it may have something to do with the way streams are being handled in the new version.

cheers

**Comment by HBYoon** [comment]
thanks for inform.
ok, I fixed that problem. module will update after code checking and testing.

**Comment by johnpool3** [comment]
Cheers for the quick turnaround. This package is good, thanks.

**Comment by HBYoon** [comment]
I did few mistakes in public processes, but anyway, now module was published.
it was a nice refactoring chance for chain method codes.
updated chain method will working more strictly :)

cheers
