### ISSUE TITLE
Why can't  excute?

### ISSUE THREAD

**Issue by cocca883** [HBYoon/node-mysql-transaction#4]
chain.query('SELECT 1');
setTimeout(function(){
      chain.query('SELECT 2');
},100);

**Comment by HBYoon** [comment]
Because autocommit is triggered at the end of queries. 
And simply, you can prevent autocommit, once.

```
chain.
query('SELECT 1').
autoCommit(false);

setTimeout(function(){
  chain.
  query('SELECT 2');
},100);
```
